export const scanData = [
  {
    id: '1',
    scanDate: '2024-11-15',
    nbrVulnerabilitites: 20,
    nbrResolvedVulnerabilitites: 9,
    detectionDate: '2024-11-15',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [
      {
        id: '20',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '19',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '18',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '17',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '16',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '15',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '14',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '13',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '12',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'non résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '-',
      },
      {
        id: '11',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '10',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '9',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '8',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '7',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '6',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '5',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '4',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '3',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '2',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
      {
        id: '1',
        scanDate: '2024-11-10',
        description: '-',
        criticality: 'faible',
        status: 'résolue',
        institution: 'BCM',
        system: 'BCM',
        correctionDate: '2024-11-11',
      },
    ],
  },
  {
    id: '2',
    scanDate: '2024-11-10',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-11-10',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '3',
    scanDate: '2024-11-12',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-11-12',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '4',
    scanDate: '2024-11-08',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-11-08',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '5',
    scanDate: '2024-11-04',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-11-04',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '6',
    scanDate: '2024-11-02',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-11-02',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '7',
    scanDate: '2024-10-30',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-30',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '8',
    scanDate: '2024-10-27',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-27',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '9',
    scanDate: '2024-10-22',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-22',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '10',
    scanDate: '2024-10-18',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-18',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '11',
    scanDate: '2024-10-15',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-18',
    institution: 'BCM',
    system: 'BCM',
    vulnerabilities: [],
  },
  {
    id: '12',
    scanDate: '2024-10-11',
    nbrVulnerabilitites: 0,
    nbrResolvedVulnerabilitites: 0,
    detectionDate: '2024-10-11',
    institution: 'BKAM',
    system: 'BKAM',
    vulnerabilities: [],
  },
]
